"""removed AA

Revision ID: 892ef6d0e06d
Revises: e7f9357ca88c
Create Date: 2025-11-08 11:40:24.169589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892ef6d0e06d'
down_revision: Union[str, Sequence[str], None] = 'e7f9357ca88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'AA')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('AA', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
