"""Added AA

Revision ID: e7f9357ca88c
Revises: 08c1205e986f
Create Date: 2025-11-08 11:39:20.383479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7f9357ca88c'
down_revision: Union[str, Sequence[str], None] = '08c1205e986f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('AA', sa.String(), nullable=True))
    op.drop_column('articles', 'last_transaction_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('last_transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'AA')
    # ### end Alembic commands ###
